"""empty message

Revision ID: dd93d791d7f1
Revises: d9a08a1e2026
Create Date: 2024-06-29 16:45:34.852153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd93d791d7f1'
down_revision = 'd9a08a1e2026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    # ### end Alembic commands ###
